version: '3'

services:

    backend:
        container_name: 'backend'
        image: metodosagilesutn2020/backend
        restart: always
        ports: 
            - "8080:8080"
        env_file:
            - ./config.env
